### ISSUE TITLE
Build modules fails on kernel 6.11

### ISSUE THREAD

**Issue by renegart** [up-division/pinctrl-upboard#15]
error messages:

> /var/lib/dkms/pinctrl-upboard/a9851f/build/spi-pxa2xx.c: In function ‘pxa2xx_spi_transfer_one’:
/var/lib/dkms/pinctrl-upboard/a9851f/build/spi-pxa2xx.c:1141:32: error: ‘struct spi_controller’ has no member named ‘cur_msg_mapped’
 1141 |                      controller->cur_msg_mapped;
      |                                ^~
> /var/lib/dkms/pinctrl-upboard/a9851f/build/spi-pxa2xx.c:2073:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
 2073 |         .remove = pxa2xx_spi_remove,
      |                   ^~~~~~~~~~~~~~~~~

**Comment by gary0124** [comment]
fix in v1.1.6
