### ISSUE TITLE
1.0.8 Failed to install on Ubuntu 18.04 Kernel 5.4.0 UpX

### ISSUE THREAD

**Issue by drhieu** [up-division/pinctrl-upboard#5]
I tried to to install the latest version of pinctrl today there's an error regarding 5.4.0 Generic not supported.
However when run 1.0.5 release. It showed downgrading from 1.0.8 and install just fine

uname -a:
Linux ruser 5.4.0-1-generic #0~upboard5-Ubuntu SMP Fri Jan 7 11:53:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gary0124** [comment]
fix in v1.1.0
