### ISSUE TITLE
 UPN-EHL01 A1.0 - GPIO Interrupt service | Not Working

### ISSUE THREAD

**Issue by SiddhantAAEON** [up-division/pinctrl-upboard#7]
On elkhart board platform, the interrupt functionality of GPIOs is not working (check attached picture)
![IMG_0030](https://github.com/up-division/pinctrl-upboard/assets/129759852/fd2752d0-b39f-40e7-a4bc-3cefb9746ae4)

**Comment by gary0124** [comment]
fix in v1.1.2
