### ISSUE TITLE
.deb package installation fails on Debian Bookworm Up Squared 7000 Pro board

### ISSUE THREAD

**Issue by Plopli** [up-division/pinctrl-upboard#8]
pinctrl-upboard_1.1.1_all.deb package

The installation enter a infinite loop with messages:
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/pinctrl-upboard/1.1.1/source/dkms.conf)

The installer seems to span process indefinitely. I did not manage to capture what exactly the process is.

**Comment by Plopli** [comment]
REMAKE_INITRD is not the problems.
The build trigger an infinite spawn of processes that looks like these:
root        1474     767  0 09:51 pts/0    00:00:00           sudo dpkg -i pinctrl-upboard_1.1.1_all.deb
root        1475    1474  0 09:51 pts/1    00:00:00             sudo dpkg -i pinctrl-upboard_1.1.1_all.deb
root        1476    1475  0 09:51 pts/1    00:00:00               dpkg -i pinctrl-upboard_1.1.1_all.deb
root        1488    1476  0 09:51 pts/1    00:00:00                 /bin/sh /var/lib/dpkg/info/pinctrl-upboard.postinst configure
root        1489    1488  0 09:51 pts/1    00:00:00                   /usr/bin/perl -w /usr/share/debconf/frontend /usr/lib/dkms/common.postinst pinctrl-upboard 1.1.1 /usr/share/pinctrl-upboard-dkms
root        1497    1489  0 09:51 pts/1    00:00:00                     /bin/sh /usr/lib/dkms/common.postinst pinctrl-upboard 1.1.1 /usr/share/pinctrl-upboard-dkms
root        2788    1497  0 09:51 pts/1    00:00:00                       /bin/bash /usr/sbin/dkms install -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        2823    2788  0 09:51 pts/1    00:00:00                         /bin/bash /usr/sbin/dkms install -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        3041    2823  0 09:51 pts/1    00:00:00                           /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        3101    3041  0 09:51 pts/1    00:00:00                             /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        3136    3101  0 09:51 pts/1    00:00:00                               /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        3468    3136  0 09:51 pts/1    00:00:00                                 /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        3528    3468  0 09:51 pts/1    00:00:00                                   /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        3563    3528  0 09:51 pts/1    00:00:00                                     /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        3903    3563  0 09:51 pts/1    00:00:00                                       /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        3963    3903  0 09:51 pts/1    00:00:00                                         /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        3998    3963  0 09:51 pts/1    00:00:00                                           /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        4338    3998  0 09:51 pts/1    00:00:00                                             /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        4398    4338  0 09:51 pts/1    00:00:00                                               /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        4433    4398  0 09:51 pts/1    00:00:00                                                 /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        4773    4433  0 09:51 pts/1    00:00:00                                                   /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        4833    4773  0 09:51 pts/1    00:00:00                                                     /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        4868    4833  0 09:51 pts/1    00:00:00                                                       /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        5208    4868  0 09:51 pts/1    00:00:00                                                         /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        5268    5208  0 09:51 pts/1    00:00:00                                                           /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        5303    5268  0 09:51 pts/1    00:00:00                                                             /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        5643    5303  0 09:51 pts/1    00:00:00                                                               /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        5703    5643  0 09:51 pts/1    00:00:00                                                                 /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        5738    5703  0 09:51 pts/1    00:00:00                                                                   /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        6078    5738  0 09:51 pts/1    00:00:00                                                                     /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        6138    6078  0 09:51 pts/1    00:00:00                                                                       /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        6173    6138  0 09:51 pts/1    00:00:00                                                                         /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        6513    6173  0 09:51 pts/1    00:00:00                                                                           /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        6573    6513  0 09:51 pts/1    00:00:00                                                                             /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        6608    6573  0 09:51 pts/1    00:00:00                                                                               /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        6948    6608  0 09:51 pts/1    00:00:00                                                                                 /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        7008    6948  0 09:51 pts/1    00:00:00                                                                                   /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        7043    7008  0 09:51 pts/1    00:00:00                                                                                     /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        7383    7043  0 09:51 pts/1    00:00:00                                                                                       /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        7443    7383  0 09:51 pts/1    00:00:00                                                                                         /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        7478    7443  0 09:51 pts/1    00:00:00                                                                                           /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        7818    7478  0 09:51 pts/1    00:00:00                                                                                             /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        7878    7818  0 09:51 pts/1    00:00:00                                                                                               /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        7913    7878  0 09:51 pts/1    00:00:00                                                                                                 /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        8253    7913  0 09:51 pts/1    00:00:00                                                                                                   /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        8313    8253  0 09:51 pts/1    00:00:00                                                                                                     /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        8348    8313  0 09:51 pts/1    00:00:00                                                                                                       /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        8688    8348  0 09:51 pts/1    00:00:00                                                                                                         /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        8748    8688  0 09:51 pts/1    00:00:00                                                                                                           /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        8783    8748  0 09:51 pts/1    00:00:00                                                                                                             /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        9123    8783  0 09:51 pts/1    00:00:00                                                                                                               /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        9183    9123  0 09:51 pts/1    00:00:00                                                                                                                 /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        9218    9183  0 09:51 pts/1    00:00:00                                                                                                                   /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        9558    9218  0 09:51 pts/1    00:00:00                                                                                                                     /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root        9618    9558  0 09:51 pts/1    00:00:00                                                                                                                       /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        9653    9618  0 09:51 pts/1    00:00:00                                                                                                                         /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root        9993    9653  0 09:51 pts/1    00:00:00                                                                                                                           /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root       10053    9993  0 09:51 pts/1    00:00:00                                                                                                                             /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root       10088   10053  0 09:51 pts/1    00:00:00                                                                                                                               /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root       10428   10088  0 09:51 pts/1    00:00:00                                                                                                                                 /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root       10488   10428  0 09:51 pts/1    00:00:00                                                                                                                                   /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root       10523   10488  0 09:51 pts/1    00:00:00                                                                                                                                     /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-amd64
root       10863   10523  0 09:51 pts/1    00:00:00                                                                                                                                       /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.1.1
root       10923   10863  0 09:51 pts/1    00:00:00                                                                                                                                         /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11-a
root       10958   10923  0 09:51 pts/1    00:00:00                                                                                                                                           /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.0-11
root       11298   10958  0 09:51 pts/1    00:00:00                                                                                                                                             /bin/sh /var/lib/dkms/pinctrl-upboard/1.1.1/source/setup.sh pinctrl-upboard 1.
root       11358   11298  0 09:51 pts/1    00:00:00                                                                                                                                               /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.1.
root       11393   11358  0 09:51 pts/1    00:00:00                                                                                                                                                 /bin/bash /usr/sbin/dkms install --force -m pinctrl-upboard -v 1.1.1 -k 6.
root       11733   11393  0 09:51 pts/1    00:00:00                                                                                                                                                   /bin/sh /var/lib/dkms/pinctrl-upb

**Comment by gary0124** [comment]
fix in v1.1.2

**Comment by Plopli** [comment]
I confirm build is working now.
