### ISSUE TITLE
upxtreme i12 spi cs0 cs1 output

### ISSUE THREAD

**Issue by hyunbin522** [up-division/pinctrl-upboard#9]
Hello, I am using upxtreme i12. 
I have to use SPI ports. In upboard cite, spi has two cs ports. 
And when I input ls /dev in ubuntu terminal, It shows spidev1.0 spidev1.1. 
But When I use the two spidev1.0 and spidev1.1 , The only chip select 0 activates.
chip select 1 does not activate... Could you help me?

**Comment by hyunbin522** [comment]
When I use this code in upboard, it works, while the upboard uses spidev2.0 spidev2.1

**Comment by gary0124** [comment]
fix in v1.1.6
